###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM  =   mpicomm
EOS      =   eos_idealgas
HYDRO    =   hydro
DENSITY  =   density
ENTROPY  = noentropy
MAGNETIC =   magnetic
GRAVITY  = nogravity
FORCING  =   forcing

REAL_PRECISION = double

#FOURIER  =   fourier_fftpack
#POWER    =   power_spectrum


#SIGNAL_HANDLING   =   signal_handling
